"""active_services: per-employee status, drop business_id

Revision ID: ac6f07a9e42f
Revises: 344e4a117d6d
Create Date: 2026-06-20 13:16:51.500649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac6f07a9e42f'
down_revision: Union[str, None] = '344e4a117d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_services', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('active_services', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_constraint('active_services_business_id_fkey', 'active_services', type_='foreignkey')
    op.create_foreign_key(None, 'active_services', 'employees', ['employee_id'], ['id'])
    op.drop_column('active_services', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_services', sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'active_services', type_='foreignkey')
    op.create_foreign_key('active_services_business_id_fkey', 'active_services', 'businesses', ['business_id'], ['id'])
    op.drop_column('active_services', 'status')
    op.drop_column('active_services', 'employee_id')
    # ### end Alembic commands ###
